name: Distribute
on:
  push:
    branches:
    - main
jobs:
  distribute:
    name: Split and release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: split upm branch
      run: |
        git config --global user.name 'github-bot'
        git config --global user.email 'github-bot@users.noreply.github.com'
        git subtree split -P "$PKG_ROOT" -b upm
        export VERSION_TAG=$(git tag -l --contains HEAD)
        git checkout upm
        git tag $(echo $VERSION_TAG | perl -pe 's/^editor_(v((0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?))$/$1/s')
        git push --tags origin upm
      env:
        PKG_ROOT: Packages/UniAPI
